## Tips to declare var without data types

In [2]:
n_price = 12 #declare int
f_price = 12.0 # declare float
s_price = '12.0' # declare string

# Case sensitive

In [4]:
t = True
T = False
print(t and T)

False


# String

In [5]:
s = 'hello'

In [3]:
?str.rjust

Docstring:
S.rjust(width[, fillchar]) -> str

Return S right-justified in a string of length width. Padding is
done using the specified fill character (default is a space).
Type:      method_descriptor


In [7]:
s.rjust(7) # 7-5 = 2 space to right

'  hello'

In [9]:
s.center(6)

'hello '

In [10]:
s.replace('l', '(ell)')

'he(ell)(ell)o'

### Remove whitespace

In [12]:
' world   '.strip()

'world'

In [15]:
?str.strip()

Docstring:
S.strip([chars]) -> str

Return a copy of the string S with leading and trailing
whitespace removed.
If chars is given and not None, remove characters in chars instead.
Type:      method_descriptor


# Set and Debug

In [ ]:
import ipdb
animals= set(['cat', 'dog', 'cat'])
animals.add('fish')

ipdb.set_trace() #Debugmode

animals.remove('cat')
animals

--Return--
None
> <ipython-input-1-053f25fb461f>(4)<module>()
      3 animals.add('fish')
----> 4 ipdb.set_trace()
      5 animals.remove('cat')

2
{'fish', 'dog'}


# Tuple

In [20]:
t = (5, 6)
t = t + (1, 2)
t

(5, 6, 1, 2)

# Find value in List and Set
### List: O(n)
### Set: O(1)

## Euclidean Division
* -10 = -4 * 3 + 2   ->   -10/3 = 4

In [5]:
print(10//3)
print(-10//3)

3
-4


# Immutable
### Tuple
### String 
* `str[0] = 'x` -> **error**

# Mutable
### List
* `list[0]=8`

### Dict (have keys is Tuple): `{(1, 2): 'a'}`

### np.array()
* Different between **is/==**: `is` for `=` and `==` for `.copy()`

### **`sorted(list)`** *vs* **`list.sort()`**

### **`reversed(list)`** *vs* **`list.reverse()`**

# Function

In [6]:
def f(a, b=2, c=3):# all var already declare put in the end
    print('a=', a)
f(2, 4, 5)

a= 2


# Numpy Matrix

In [1]:
import numpy as np

In [7]:
a = np.array([[1, 2, 3, 4], [5, 6, 7]])
a.shape

(2,)

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
b = np.array([0, 2, 0, 1])
a[np.arange(4), b]

array([ 1,  6,  7, 11])

In [11]:
a.dtype

dtype('int32')

In [14]:
x = np.array([1, 2.36], dtype=np.int64)
x

array([1, 2], dtype=int64)

In [17]:
x = np.array([[1, 2], [5, 6]], dtype=np.float64)
y = np.array([[5, 6], [3, 4]], dtype=np.float64)

### Hamadard product

In [18]:
x * y

array([[ 5., 12.],
       [15., 24.]])

### Dot product

In [19]:
x.dot(y)

array([[11., 14.],
       [43., 54.]])

In [20]:
x = np.array([[1, 2], [3, 4]])
x.T

array([[1, 3],
       [2, 4]])

In [21]:
np.sum(x, axis=0)

array([4, 6])

In [22]:
np.sum(x, axis=1)

array([3, 7])

## `empty_like` = `zeros_like`

In [23]:
y = np.empty_like(x)
y

array([[0, 0],
       [0, 0]])

In [25]:
y = np.zeros_like(x)
y

array([[0, 0],
       [0, 0]])

# Tile: replicate matrix

In [27]:
y = np.tile(x, (4, 1))
y

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

## Don't need to have 2 same dimension matrix to sum them

In [32]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
y = np.array([1, 0, 1])
x + y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [29]:
np.sum(x, y)

TypeError: only integer scalar arrays can be converted to a scalar index

# Assignment
## 1

In [3]:
x=3.14
print(type(x))

x=-34
print(type(x))

x=True
print(type(x))

x=False
print(type(x))

x=3.0
print(type(x))

<class 'float'>
<class 'int'>
<class 'bool'>
<class 'bool'>
<class 'float'>


# 2

In [9]:
x=6+12-3
print(x, type(x))

x=2*3.0
print(x, type(x))

x=- - 4
print(x, type(x))

x=10/3
print(x, type(x))

x=10.0/3.0
print(x, type(x))

x=(2+3)*4
print(x, type(x))

x=2+3*4
print(x, type(x))

x=2**3+1
print(x, type(x))

x=2.1**2.0
print(x, type(x))

x=2.2**3.0
print(x, type(x))

15 <class 'int'>
6.0 <class 'float'>
4 <class 'int'>
3.3333333333333335 <class 'float'>
3.3333333333333335 <class 'float'>
20 <class 'int'>
14 <class 'int'>
9 <class 'int'>
4.41 <class 'float'>
10.648000000000003 <class 'float'>


# 3

In [14]:
print(3 > 4)
print(4.0 > 3.99)
print(4 > 4)
print(4 > + 4)
print(2 + 2 == 4)
print((5.0 - 3.0) != (3.0 - 1.0))
print(3 > 4 or ( 2 < 3 and 9 > 10))
print(4 > 5 or 3 < 4 and 9 > 8)
print(not( 4 > 3 and 100 > 6))

False
True
False
False
True
False
False
True
False


## 4

In [1]:
x= 3 + 5.0
print(x, type(x))

x= 5/2
print(x, type(x))

x= 5/2 == 5/2.0
print(x, type(x))

x= 5/2.0
print(x, type(x))

x= round(2.6)
print(x, type(x))

x= int(2.6)
print(x, type(x))

x= 2.0 + 5.0
print(x, type(x))

x= 5*2 == 5.0 * 2.0
print(x, type(x))


8.0 <class 'float'>
2.5 <class 'float'>
True <class 'bool'>
2.5 <class 'float'>
3 <class 'int'>
2 <class 'int'>
7.0 <class 'float'>
True <class 'bool'>


## 5

In [25]:
x="a" + "bc"
print(x)

x=3 * "bc"
print(x)

try:
    x="3" * "bc"
except:
    print('3 must be int')

x="abcd" [2]
print(x)

x="abcd" [-1]
print(x)

x="abcd" [0:2]
print(x)

x="abcd" [:2]
print(x)

x="abcd" [2:]
print(x)

s = 'Python is Fun!'
print(x)

x=s[1:12:2]
print(x)

x=s[1:12:3]
print(x)

x=s[::2]
print(x)

abc
bcbcbc
3 must be int
c
d
ab
ab
cd
cd
yhni u
yoiF
Pto sFn


## 6

In [64]:
x = (1, 2, (3, 'John' , 4), 'Hi')
x[0]

1

In [65]:
type(x)

tuple

In [66]:
a=x[0]
print(a, type(a))

a=x[2]
print(a, type(a))

a=x[-1]
print(a, type(a))

a=x[2][2]
print(a, type(a))

a=x[2][-1]
print(a, type(a))

a=x[-1][-1]
print(a, type(a))

try:
    a=x[-1][2]
except:
    print('Not in tuple')

a=x[0:1]
print(a, type(a))

a=x[0:-1]
print(a, type(a))

a=len(x)
print(a, type(a))

a=2 in x
print(a, type(a))

a=3 in x
print(a, type(a))

try:
    x[0] = 8
    print(x)
except:
    print('tuple object does not support item assignment')

1 <class 'int'>
(3, 'John', 4) <class 'tuple'>
Hi <class 'str'>
4 <class 'int'>
4 <class 'int'>
i <class 'str'>
Not in tuple
(1,) <class 'tuple'>
(1, 2, (3, 'John', 4)) <class 'tuple'>
4 <class 'int'>
True <class 'bool'>
False <class 'bool'>
tuple object does not support item assignment


## 7

In [67]:
x = [1, 2, ( 3, 'John' , 4), 'Hi']

In [68]:
a=x[0]
print(a, type(a))

a=x[2]
print(a, type(a))

a=x[-1]
print(a, type(a))

a=x[2][2]
print(a, type(a))

a=x[0:1]
print(a, type(a))

a=2 in x
print(a, type(a))

x[0]=8
print(x)

1 <class 'int'>
(3, 'John', 4) <class 'tuple'>
Hi <class 'str'>
4 <class 'int'>
[1] <class 'list'>
True <class 'bool'>
[8, 2, (3, 'John', 4), 'Hi']


## 8

In [84]:
listA = [ 1, 4, 3, 0]
listB = [ 'x' , 'z' , 't' , 'q' ]

In [85]:
listA.sort
listA

[1, 4, 3, 0]

In [86]:
listA.sort()
listA

[0, 1, 3, 4]

In [87]:
listA.insert(0, 100)
listA.remove(3)
listA.append(7)
listA

[100, 0, 1, 4, 7]

In [88]:
listB.sort()
listB.pop()
print(listB.count('a'))
listB

0


['q', 't', 'x']

In [89]:
try:
    listB. remove('a')
except:
    print('a not in tuple')

a not in tuple


In [90]:
listA.extend([4, 1, 6, 3, 4])
listA

[100, 0, 1, 4, 7, 4, 1, 6, 3, 4]

In [91]:
listA.count(4)

3

In [92]:
listA.index(1)

2

In [93]:
listA.pop(4)
listA

[100, 0, 1, 4, 4, 1, 6, 3, 4]

In [94]:
listA.reverse()
listA

[4, 3, 6, 1, 4, 4, 1, 0, 100]

## 9
#### Different between `bList=aList` and `bList=aList.copy()`
##### With `bList=aList.copy()`

In [99]:
aList = [0, 1, 2, 3, 4, 5]
bList = aList.copy()
print(bList)

[0, 1, 2, 3, 4, 5]


In [100]:
aList[2]='Hello'
aList = bList
print(aList)

[0, 1, 2, 3, 4, 5]


##### With `bList=aList`

In [101]:
aList = [0, 1, 2, 3, 4, 5]
bList = aList
print(bList)

[0, 1, 2, 3, 4, 5]


In [102]:
aList[2]='Hello'
aList = bList
print(aList)

[0, 1, 'Hello', 3, 4, 5]


In [103]:
print(aList == bList)

True


In [104]:
print(aList is bList)

True


In [105]:
aList

[0, 1, 'Hello', 3, 4, 5]

In [106]:
bList

[0, 1, 'Hello', 3, 4, 5]

In [107]:
cList = [ 6, 5, 4, 3, 2]
dList = []
for num in cList:
    dList. append(num)
print(cList == dList)
print(cList is dList)

True
False


* `is` will return `True` if two variables point to the same object, `==` if the objects referred to by the variables are equal

In [110]:
cList[ 2] = 20
print(cList)
print(dList)

[6, 5, 20, 3, 2]
[6, 5, 4, 3, 2]


## 10

In [111]:
animals = {'a':'aardvark', 'b':'baboon' ,'c':'coati'}
animals['d'] = 'donkey'
animals

{'a': 'aardvark', 'b': 'baboon', 'c': 'coati', 'd': 'donkey'}

In [112]:
animals['c']

'coati'

In [114]:
try: 
    animals['donkey']
except:
    print('donkey is not in keys')

donkey is not in keys


In [115]:
len(animals)

4

In [116]:
animals['a'] = 'anteater'
animals['a']

'anteater'

In [118]:
len(animals['a'])

8

In [119]:
print('baboon' in animals)

False


In [121]:
print('donkey' in animals.values())

True


In [127]:
print('b' in animals)

True


#### `animals` is equal to `animals.keys()`

In [128]:
animals.keys()

dict_keys(['a', 'b', 'c', 'd'])

In [129]:
del animals['b']
len(animals)

3

In [130]:
animals.values()

dict_values(['anteater', 'coati', 'donkey'])

## 11

In [ ]:
def count_vowel(str_inputs):
    vowels = ['u', 'e', 'o', 'a', 'i']
    count = 0
    for str_input in str_inputs:
        if str_input in vowels:
            count = count + 1
    return count
str_inputs = input()
print('Number of vowel:', count_vowel(str_inputs))

In [1]:
?sum

Signature: sum(iterable, start=0, /)
Docstring:
Return the sum of a 'start' value (default: 0) plus an iterable of numbers

When the iterable is empty, return the start value.
This function is intended specifically for use with numeric values and may
reject non-numeric types.
Type:      builtin_function_or_method


In [148]:
import functools as ft
list_input = [1, 2, 3, 4, 5]
sum_list = ft.reduce(lambda index0, index1: print(index1), list_input)
print(sum_list)

2
3
4
5
None


In [153]:
import functools as ft
list_input = [1, 2, 3, 4, 5]
sum_list = ft.reduce(lambda index0, index1: (index0 if index0 % 2 == 0 else 0) 
                     + (index1 if index1 % 2 == 0 else 0), list_input)
print(sum_list)

6


In [156]:
import numpy as np
v_1 = [3, 4, 5]
print(np.linalg.norm(v_1))

7.0710678118654755


In [158]:
v_1 = [3, 4, 5]
print(np.linalg.norm(v_1, ord=1))

12.0


In [161]:
v_1=np.array([2, 4, 5])
v_2=np.array([4, 5, 6])
print(v_1.T.dot(v_2))

58
